### ISSUE TITLE
Assets

### ISSUE THREAD

**Issue by davidmayr** [Robinfr/electron-react-typescript#30]
Whats the best way to use assets in this Template?

**Comment by Robinfr** [comment]
Assets as in images? You can simply import static files as you would with normal modules since there is a loader setup in the Webpack config for most common image formats.

Example of an image can be found here: https://github.com/Robinfr/electron-react-typescript/blob/master/src/renderer/components/Counter.tsx

If you need different types of assets, you'll need to figure out which Webpack loaders there are available for that type of assets and set that up yourself.
